Working with push

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -56,6 +56,7 @@ nuget_baseurl=${NUGET_BASEURL:-$nuget_baseurl}
 nuget_baseurl=${BUILDKITE_PLUGIN_DOTNET_NUGET_BASE_URL:-$nuget_baseurl}
 nuget_auth_user=${BUILDKITE_PLUGIN_DOTNET_NUGET_AUTH_USER:-$NUGET_AUTH_USER}
 nuget_auth_key=${BUILDKITE_PLUGIN_DOTNET_NUGET_AUTH_KEY:-$NUGET_AUTH_KEY}
+#nuget_packages=${BUILDKITE_PLUGIN_DOTNET_NUGET_PACKAGES}
 pull=${BUILDKITE_PLUGIN_DOTNET_NUGET_PULL:-1}
 if [ $pull -gt 0 ]; then
     $docker pull $image
@@ -69,6 +70,11 @@ export NUGET_AUTH_USER=$nuget_auth_user
 export NUGET_AUTH_KEY=$nuget_auth_key
 
 # folders
+wrkdir=/build
+if [ -d "$src" ]; then
+    wrkdir=/build/$src
+fi
+
 if [ -d "$src" ]; then
     if [ -e "$tpl" ]; then
         cp $tpl $src/NuGet.Config
@@ -82,10 +88,6 @@ if [ ! -d "$tmp" ]; then
 fi
 
 function dotnet_execute() {
-    wrkdir=/build
-    if [ -d "$src" ]; then
-        wrkdir=/build/$src
-    fi
     env > .env
     # $docker run -e "NUGET_BASEURL=$nuget_baseurl" -e "NUGET_AUTH_USER=$nuget_auth_user" -e "NUGET_AUTH_KEY=$nuget_auth_key" -v $pwd:/build -w $wrkdir --entrypoint $dotnet $image $*
     $docker run --env-file .env -v $pwd:/build -w $wrkdir --entrypoint $dotnet $image $*
@@ -106,4 +108,18 @@ dotnet_execute pack -c $configuration /p:Version=$version --include-symbols -o $
 
 # push
 
-echo push
+# TODO: check packages input
+
+pack_dir=$wrkdir/$tmp/$configuration
+if [ -d "$pack_dir" ]; then
+    packages=$(ls $pack_dir/*.nupkg)
+    for p in $packages
+    do
+        echo $p
+
+        #dotnet_execute nuget push $p -k $nuget_auth_user:$nuget_auth_key -s $NUGET_BASEURL$NUGET_PACKAGE/
+    done
+else
+    echo "Cannot find any packages to push in ($pack_dir)"
+    exit 1
+fi
